### ISSUE TITLE
[Sourcing][Accessibility][ATL Testing][Multi-input with dialog][Sep18]The value help button is looks dummy as on activating it, the dialog is getting closed.

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#10386]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
The value help button is looks dummy as on activating it, the dialog is getting closed.
<img width="452" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/88182358/1bc0bcde-ac17-45ad-a02d-354f3111e907">

#### If this is a bug, please provide steps for reproducing it.
tested on multi-input mobile mode

#### Is there anything else we should know?
Reported by ATL
This is not the case happening with UI5. None of the dialogs have toggle button again to close the multi-input value help
https://sapui5.hana.ondemand.com/#/entity/sap.m.MultiInput/sample/sap.m.sample.MultiInputValueHelp

**Comment by droshev** [comment]
we need to downport this to `ng15`

**Comment by droshev** [comment]
fixed with `0.43.6`

**Comment by I543348** [comment]
ATL Re-verification

**Comment by sagar7259** [comment]
Hello,

On activating the value help button within the dialog, the dialog is not getting closed instead the focus itself is moving back to the main screen on the input field from where it was invoked.
![image](https://github.com/SAP/fundamental-ngx/assets/143692208/baa207df-db23-467a-a413-3c6237ddbbef)

This is still an issue and needs to be fixed.

@rvamudha please reopen the ticket.

Regards,
Sagar(ATL team)

**Comment by droshev** [comment]
@sagar7259 which version did you run the test on?

**Comment by sagar7259** [comment]
Hello Team,

This is been fixed with 1.43.0 version and its working as expected. Hence this ticket can be closed.

Regards,
Sagar
