### ISSUE TITLE
Issue with Theming Service while applying theme

### ISSUE THREAD

**Issue by sameesheikh25** [SAP/fundamental-ngx#10700]
#### Is this a bug, enhancement, or feature request?
**BUG**

#### Describe your proposal.

We have encountered one issue from **theming service** where happens while applying different **horizon themes** in our application. We load our application in **SAP Morning Horizon** theme which is the default theme using Theming Service Library provided from NGX, the expected theme or styling is not correctly applied. Instead, when we try to clear our cache and do Hard Reload, sometimes the application loads in **Quartz theme** by default.

This issues occurs sporadically, when we do empty cache and hard reload. I have also attached screenshots for reference. 

As shown in the screen shots, we have **SAP Morning horizon** theme selected by default.

<img width="1002" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/102856000/09761fe4-67c7-4de9-aaea-db1dd9bc51b1">

**Current Behavior:**

When we load application, it loads in **Quartz theme** by default.

<img width="1174" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/102856000/05d15f71-3eb3-43eb-947d-e0afcfc76807">

**Expected Behavior:**

When we again do normal reload, the application loads in Horizon theme as expected.

<img width="1171" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/102856000/1b6a3811-55f3-4f5b-997d-4278656972d7">

I have also tried debugging the source code and found out that one place, the default_theme value getting set to "sap_fiori_3" which might be causing this issue. 

<img width="738" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/102856000/a466e708-28cc-4a8f-abe5-3e52dbccd22b">

We also pass correct theme parameter into setTheme method of Theming Service as expected. 

This is the versions we use for ngx libraries in our application.

**"@angular/core": "^16.2.8",
"@fundamental-ngx/core": "^0.45.1",
"@sap-theming/theming-base-content": "11.6.8",
"fundamental-styles": "0.28.3"**

**Comment by N1XUS** [comment]
Hello @sameesheikh25. Thank you for your interest in theming functionality. Could you please provide more code of how you initialize themignService, do you also use `withConfig` or `provideTheming()` function to override default configuration that is setting default theme as fiori3?

**Comment by sameesheikh25** [comment]
Hi @N1XUS, yes I have tried setting 'sap-horizon' as default theme using withConfig method. I have also provided code snippet for reference
`ThemingModule.withConfig({ defaultTheme: 'sap_horizon' })`
But this also doesn't seems to be working. It stills sometimes load the application in fiori3

**Comment by N1XUS** [comment]
@sameesheikh25 and where did you found this code? https://user-images.githubusercontent.com/102856000/274251997-a466e708-28cc-4a8f-abe5-3e52dbccd22b.png

**Comment by sameesheikh25** [comment]
@N1XUS its there in **main.js** file. Its automatically being loaded from theming service library I guess. Because we haven't initialised any default theme value in our code base. Also these codebase (https://user-images.githubusercontent.com/102856000/274251997-a466e708-28cc-4a8f-abe5-3e52dbccd22b.png) gets loaded in our dev landscape and not locally.

**Comment by N1XUS** [comment]
@sameesheikh25 We've released new RC version, could you please run checks against this version? v0.46.0-rc.94

**Comment by sameesheikh25** [comment]
By delaying the call for setTheme() with setTimeout() interval, we can clearly see that by default (sap_fior_3) getting set from theming service. 

Overriding default theme from theming module to set default horizon(sap_horizon), setting quartz(sap_fiori_3) from theming service did not happen. But if the user has selected some other theme from preference ex. horizon evening(sap_horizon_dark), then we'll see theme switching from horizon to evening after the setTimeout interval.

**Comment by N1XUS** [comment]
@sameesheikh25 So, the issue here is that you do not provide theme by default, and relying on the user configured theme, right?

**Comment by N1XUS** [comment]
@sameesheikh25 If so, what you can do is to postpone themingService initialization (calling `init()` method) until you load all necessary information to apply theming. Here's a simple example of postponing theming initialization https://stackblitz.com/edit/fo4bjs?file=src%2Findex.html,src%2Fmain.ts,src%2Fapp%2Ftheme-switcher-example.component.ts,src%2Fapp%2Ftheme-switcher-example.component.html

**Comment by dhivya910** [comment]
Hi @N1XUS , this issue still occurs sporadically when we try to empty cache and hard reload in UI, after applying the theme.
